export const farmsMocked = [
  {
    id: String(Math.random()),
    document: '424324234',
    productor_name: 'Fazendeiro',
    farm_name: 'Teste',
    state: 'São Paulo',
    city: 'Araçatuba',
    total_area_farm: 1000000,
    total_area_agriculture: 10000,
    total_area_vegetation: 15000,
    cultures: ['Cana', 'Milho', 'Soja'],
  },
  {
    id: String(Math.random()),
    document: '424324234',
    productor_name: 'Fazendeiro',
    farm_name: 'Teste',
    state: 'São Paulo',
    city: 'Araçatuba',
    total_area_farm: 1000000,
    total_area_agriculture: 10000,
    total_area_vegetation: 15000,
    cultures: ['Cana', 'Milho', 'Soja'],
  },
  {
    id: String(Math.random()),
    document: '424324234',
    productor_name: 'Fazendeiro',
    farm_name: 'Teste',
    state: 'São Paulo',
    city: 'Araçatuba',
    total_area_farm: 1000000,
    total_area_agriculture: 10000,
    total_area_vegetation: 15000,
    cultures: ['Cana', 'Milho', 'Soja'],
  },
];
